### ISSUE TITLE
We need to respond to Larry about wildcards

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/patma#134]
Larry Hastings on the python-dev thread is making a case for `?` as the wildcard. We need to provide a response to this.

**Comment by brandtbucher** [comment]
I was thinking of writing up a response to that post later today. It leans pretty heavily on a couple of misunderstandings that I hope to clear up.

**Comment by dmoisset** [comment]
I may have misread his email, but he's not asking for `?`, but instead relaxing the constrains (on double binding) to allow `_` be just any other name used as non-bind by convention

**Comment by Tobias-Kohn** [comment]
I do not see the `?` part from the archive, so I am not entirely sure we are talking about the same thing.  A lot of the message I can see is about I18N, which I still believe is quite a non-issue, anyway.

One thing that I just picked up:

> Consider that Python already permits multiple assignments in a 
single expression:
`(x:="first", x:="middle", x:="last")`

The message that we might have to bring across is that _patterns are not expressions_.  Yes, we borrow a lot of syntax already common in expressions, but with a different meaning, due to the wildly different context.

Patterns are much closer to parameter lists than to expressions.  And lo and behold: you cannot define a function with two parameters sharing the same name.

There might be some valid reason to reconsider this some time in the future, but I really cannot think of a good reason right now.  Moreover, with all this discussion about the foot gun lately, I am surprised that there is no critique of a feature that is meant to help prevent errors.

**Comment by dmoisset** [comment]
I answered about performance issues. I just saw the message regarding `?`, it was in a broken thread titled "Re: Python-Dev Digest, Vol 204, Issue 75" out of the main thread

**Comment by Tobias-Kohn** [comment]
@dmoisset  Thanks!  I have now found it.

**Comment by Tobias-Kohn** [comment]
It seems a bit like the entire statement is spread over two posts, really.  

> If we forego these two exceptions, `_` can go back to behaving like any other identifier.  It becomes an idiom rather than a special case.

> Personally I prefer it [`?`] to special-casing `_`.

If I understand it correctly, the argument is for introducing a whole new special token so as to not make `_` slightly special (but perhaps use it as a throwaway nonetheless).  And instead of following the trail of virtually _all_ other programming languages with pattern matching on using `_`, we should pick up the way shell scripting spells wildcards?  Why?  Are there any actual arguments given for why this would be any better?  What makes shell scripting a better basis than all other existing models?

I think @dmoisset has provided a very nice application as of why doing the assignment (or not) really matters.

But what are really the consequences of `_`'s special behaviour?

1. It is unfortunately not possible to have something like `case _: print(_)`, it must be spelled as `case x: print(x)`.
2. We do not need to invent new variables for values we don't care about as in `case (_, _, x):` vs. `case (arg0, arg1, x)`.
3. There is no need for special syntax and `?` remains free for future uses (including to accept it as part of a name or pick up the entire load/store problematic for some future PEP).
4. We protect `_` from being overriden by pattern matching, so that pattern matching in fact plays very nicely with I18n and interactive consoles.
5. It extends its current and traditional use as a quasi-wildcard in unpacking assignments.

Switching to `?` as wildcard would allow us to write `case _:` so as to bind the subject to `_`.  Is there any other advantage that I am just not seeing here?

**Comment by gvanrossum** [comment]
I just [responded](https://mail.python.org/archives/list/python-dev@python.org/message/K5OR4QNSF2VVHJ43QTQ2AJXMLHHVA7HE/) to Larry.

I propose not to follow up on this point further unless a real firestorm breaks out. If Larry doesn't agree, we should just agree to disagree.

**Comment by gvanrossum** [comment]
BTW, there's also the use of `_` as the "last expression printed" in the REPL. This is preserved:
```
>>> match 2:
...  case 1: "A"
...  case _: "B"
... 
'B'
>>> _
'B'
>>> 
```

**Comment by gvanrossum** [comment]
It appears that Larry is agreeing to disagree. He sent a calm message reiterating his concerns but ending with

> My goal in starting this discussion was to see if we could find a compromise everyone could live with.  People who want to use '_' for wildcard pattern could do so, people who didn't like '_' having a special meaning in this one context would be appeased.  The message I'm getting is "this compromise won't work".  **Okay, fair enough.  I don't plan to pursue it any further.**

(Emphasis mine.)

**Comment by gvanrossum** [comment]
Let's just close this.
