### ISSUE TITLE
New instruction issues with the reference implementation 

### ISSUE THREAD

**Issue by thautwarm** [gvanrossum/patma#99]
I noticed so far @brandtbucher has added [4 new instructions], named after `MATCH_*`.

Not sure people's attitudes towards adding so many new instructions, but I'm pretty sure to implement pattern matching needs no new instructions.

There can be a few reasons for you to add them, and could you please answer the following questions? I think you shall give some valid and convincing concerns.

1. New instructions for what? Performance gain, or simplifying the implementation?
2. If you consider performance gain, could you show a benchmark with comparisons?
3. If you consider simplifying the implementation, could you give some good reasons for doing this? We need to negotiate on this later.

P.S:
I did [implement a Python pattern matching library](https://github.com/thautwarm/moshmosh#case-study--pattern-matching) even close to PEP 622 within pure python, supporting Python 3.4+, and it seems reasonably fast. **I don't see a performance hit when comparing with equivalent if-else statements**, besides, mine is already **10-200x faster than the popular dynamic contract library [PamPy](https://github.com/santinic/pampy)**, this is a pretty acceptable performance. [A simple benchmark of my library](https://github.com/thautwarm/moshmosh/blob/master/benchmark.py) could be found here.

**Comment by brandtbucher** [comment]
Hi @thautwarm.

Unlike the PEP, the reference implementation isn't really open to outside discussion or input. It's just that: a reference. Its purpose is to inform the design, give people a chance to try out our new feature, and create a foundation for Python's future pattern matching implementation (if any).

I assure you that there are advantages that justify the addition of the few new opcodes. I don't feel the "need to negotiate" or justify them to you (or anyone else) at this stage. Sorry. The implementation has changed greatly in many places since we first started working on the proposal several months ago, and I have no doubts that it will change further.

When the PEP is accepted (if ever) and the implementation is merged, you are more than welcome to open issues on the Python bug tracker proposing improvements to it. If you find bugs in the current implementation (not suggestions or improvements, but places where we differ from the PEP's prescribed behavior), please open issues here in this tracker to report them.
